CHOST="x86_64-pc-linux-musl"
LDFLAGS="-Wl,-O2 -Wl,--as-needed"
COMMON_FLAGS="-march=sandybridge -O3 -pipe"
CFLAGS="${COMMON_FLAGS} -flto=thin"
CXXFLAGS="${COMMON_FLAGS} -flto=thin"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
COMMON_RUSTFLAGS="-Ctarget-cpu=sandybridge -Copt-level=3 -Ccodegen-units=4"
RUSTFLAGS="${COMMON_RUSTFLAGS} -Clinker=clang -Clinker-plugin-lto=yes -Clink-arg=-flto=thin"

CMAKE_MAKEFILE_GENERATOR=ninja
ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"

MICROCODE_SIGNATURES="-s 0x000206d7"

EMERGE_DEFAULT_OPTS="--verbose --jobs=12 --load-average=11 --jobs-tmpdir-require-free-gb=0 --autounmask-write=y --with-bdeps=y --quiet-build=y --keep-going=y --buildpkg"
MAKEOPTS="-j12 -l11"
FEATURES="parallel-fetch parallel-install -collision-detect -protect-owned"
#CCACHE_DIR="/var/cache/ccache"
AUTOCLEAN="yes"
#CCACHE_SIZE="5GiB"
#PORTAGE_NICENESS="15"
#USE_NO="-accessibility -apache2 -aqua -atm -berkdb -bluetooth -crypt -doc -gnome -gnome-keyring -ieee1394 -joystick -kwallet -libressl -mysql -networkmanager -oss -postscript -pulseaudio -systemd -wifi"
#USE_DEFAULT="X alsa bash-completion branding btrfs cdda cdr clang cups curl dbus dvd dvdr djvu dri elogind ffmpeg flac fontconfig gif gimp git gtk gtk2 gtk3 icu ipv6 jpeg jpeg2k libnotify kde lz4 matroska mp3 mp4 mtp ncurses nls nsplugin opengl pdf plasma png policykit qt5 scanner screencast smp spell ssl theora tiff truetype udev udisks unicode upnp upnp-av upower usb v4l x264 wayland xcomposite xft xinerama zsh zsh-completion zstd"
#USE_SWAY="X alsa zsh-completion btrfs clang curl dbus djvu dir elogind git icu smp udev udisks unicode upnp upnp-av wayland zstd pipewire"
#USE="${USE_SWAY} ${USE_NO} ${USE_DEFAULT}"
GENTOO_MIRRORS="https://gentoo.c3sl.ufpr.br/ http://gentoo.c3sl.ufpr.br/ rsync://gentoo.c3sl.ufpr.br/gentoo/ http://distfiles.gentoo.org http://www.ibiblio.org/pub/Linux/distributions/gentoo"

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORTAGE_TMPDIR=/var/tmp
PORTAGE_ELOG_CLASSES="log warn error"
PORTAGE_ELOG_SYSTEM="echo save"
PORTAGE_LOGDIR="/var/log/portage"
VIDEO_CARDS="radeon r600"
INPUT_DEVICES="libinput"

ELIBC="musl"
L10N="pt-BR"
LINGUAS="pt_BR"
LC_MESSAGES=C.UTF-8
QEMU_SOFTMMU_TARGETS="arm x86_64"
QEMU_USER_TARGETS="x86_64"
PYTHON_TARGETS="python3_12 python3_13"
PYTHON_SINGLE_TARGET="python3_12"
#LLVM_TARGETS="X86 AArch64 AMDGPU ARM AVR BPF Hexagon Lanai MSP430 Mips NVPTX PowerPC RISCV Sparc SystemZ VE WebAssembly XCore"
